changelog:
  exclude:
    labels:
      - dependencies
      - github_actions
      - ignore-for-release-notes
  categories:
    - title: New Features 🎉
      labels:
        - enhancement
    - title: Defects 🧐
      labels:
        - defect
    - title: Bug fixes 🛠
      labels:
        - bug
    - title: Technical updates 🔧
      labels:
        - dependencies
    - title: Other Changes
      labels:
        - "*"
