name: Delete Workflow Artifacts

on:
  workflow_call:
    inputs:
      excludes:
        required: false
        type: string
jobs:
  delete-artifacts:
    runs-on: ubuntu-22.04
    permissions:
      actions: write 
    steps:
      - run: |
        
         excludes="$(echo "${{ inputs.excludes }}")"
         excludes="$(echo "${excludes%%*( )}" | jq -R -r -s -c 'split("\n") | map(select(length>0))')"
         artifacts="$(gh api \
           -H "Accept: application/vnd.github+json" \
           -H "X-GitHub-Api-Version: 2022-11-28" \
           /repos/$OWNER/$REPO/actions/runs/${{ github.run_id }}/artifacts \
           | jq --arg excludes "$excludes"  '[.artifacts[] | select([.name] | inside([$excludes]) | not ) | .id ] | @sh')"
      
         for artifactId in $artifacts
         do
            artifactId=${artifactId//\"/}
            if [[ $artifactId ]] ; then
              echo "Deleting $artifactId artifact..."
              gh api \
                --method DELETE \
                -H "Accept: application/vnd.github+json" \
                -H "X-GitHub-Api-Version: 2022-11-28" \
                /repos/$OWNER/$REPO/actions/artifacts/$artifactId
            fi
         done
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          OWNER: ${{ github.repository_owner }}
          REPO: ${{ github.event.repository.name }}
