name: Test

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Create file
        run: |
          echo "hello" > hello.txt
          echo "hello" > hello2.txt
          
      - name: Upload Hello
        uses: actions/upload-artifact@v4
        with:
          name: hello
          path: hello.txt
          retention-days: 1
          
      - name: Upload Hello 2
        uses: actions/upload-artifact@v4
        with:
          name: hello2
          path: hello2.txt
          retention-days: 1
            
  clean-artifacts:
    needs: build
    runs-on: ubuntu-22.04
    steps:
    
      - run: |
         artifacts="$(gh api \
           -H "Accept: application/vnd.github+json" \
           -H "X-GitHub-Api-Version: 2022-11-28" \
           /repos/$OWNER/$REPO/actions/runs/${{ github.run_id }}/artifacts \
           --jq '[.artifacts[] | .id]')"
      
         echo $artifacts 
         echo ${{ fromJson($artifacts) }}
         for artifactId in $artifacts
         do
            echo "Deleting $artifactId..."
            gh api \
           --method DELETE \
           -H "Accept: application/vnd.github+json" \
           -H "X-GitHub-Api-Version: 2022-11-28" \
           /repos/$OWNER/$REPO/actions/artifacts/$artifactId
         done
        env:
          GH_TOKEN: ${{ github.token }}
          OWNER: ${{ github.repository_owner }}
          REPO: ${{ github.event.repository.name }}

        
        